apiVersion: v1
kind: Secret
metadata:
  name: agenda-secret
  namespace: agenda
type: Opaque
stringData:
  POSTGRES_USER: agenda
  POSTGRES_PASSWORD: agenda
  POSTGRES_DB: agenda
  DATABASE_URL: "host=postgres port=5432 user=agenda password=agenda dbname=agenda sslmode=disable"
